.SUFFIXES: .java

$(THEOS_OBJ_DIR)/%.java.o: %.java
	@touch $@
	$(ECHO_COMPILING)$(TARGET_JAVAC) $(TARGET_JAVAC_ARGS) -d $(THEOS_CLASSES_DIR)/ $^$(ECHO_END)

$(THEOS_CLASSES_DIR): $(THEOS_OBJ_DIR)
	@cd $(THEOS_OBJ_DIR); mkdir -p $(THEOS_CLASSES_DIR_NAME)
