ifeq ($(_THEOS_RULES_LOADED),)
include $(THEOS_MAKE_PATH)/rules.mk
endif

_THEOS_INTERNAL_LDFLAGS += -Wl,--gc-sections -e main

.PHONY: internal-firmware-all_ internal-firmware-stage_ internal-firmware-compile

ifeq ($(_THEOS_MAKE_PARALLEL_BUILDING), no)
internal-firmware-all_:: $(_OBJ_DIR_STAMPS) $(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).hex
else
internal-firmware-all_:: $(_OBJ_DIR_STAMPS)
	$(ECHO_NOTHING)$(MAKE) $(_THEOS_NO_PRINT_DIRECTORY_FLAG) --no-keep-going \
		internal-firmware-compile \
		_THEOS_CURRENT_TYPE=$(_THEOS_CURRENT_TYPE) THEOS_CURRENT_INSTANCE=$(THEOS_CURRENT_INSTANCE) _THEOS_CURRENT_OPERATION=compile \
		THEOS_BUILD_DIR="$(THEOS_BUILD_DIR)" _THEOS_MAKE_PARALLEL=yes$(ECHO_END)

internal-firmware-compile: $(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).hex
endif

$(eval $(call _THEOS_TEMPLATE_DEFAULT_LINKING_RULE,$(THEOS_CURRENT_INSTANCE).elf))

$(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).eep: $(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).elf
	$(ECHO_NOTHING)$(TARGET_OBJCOPY) -O ihex $(_THEOS_TARGET_EEPROM_OBJCOPYFLAGS) $< $@$(ECHO_END)
$(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).hex: $(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).elf $(THEOS_OBJ_DIR)/$(THEOS_CURRENT_INSTANCE).eep
	$(ECHO_NOTHING)$(TARGET_OBJCOPY) -O ihex $(_THEOS_TARGET_OBJCOPYFLAGS) $< $@$(ECHO_END)

internal-firmware-stage_::
	#$(ECHO_NOTHING)$(THEOS_ARDUINO_TEENSY_TOOLS_PATH)/teensy_post_compile -file=$(THEOS_CURRENT_INSTANCE) -path=$(call __clean_pwd,$(THEOS_OBJ_DIR)) -tools=$(THEOS_ARDUINO_TEENSY_TOOLS_PATH)/$(ECHO_END)
	#$(ECHO_NOTHING)$(THEOS_ARDUINO_TEENSY_TOOLS_PATH)/teensy_reboot$(ECHO_END)
